//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App015_20250701_EF6_SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defect
    {
        public long index { get; set; }
        public Nullable<long> photo_x { get; set; }
        public Nullable<long> photo_y { get; set; }
        public Nullable<decimal> world_x { get; set; }
        public Nullable<decimal> world_y { get; set; }
        public Nullable<decimal> roll_x { get; set; }
        public Nullable<decimal> roll_y { get; set; }
        public string kind { get; set; }
        public Nullable<decimal> reliability { get; set; }
        public Nullable<long> image_index { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
